#!/bin/bash

get_help() {
	echo "tex3pdf [options] [-f FILENAME] [-o OUTPUT]"
	echo "-h	get this help"
	echo "-f 	specify input tex file, default is main.tex"
	echo "-o	specify output pdf file, default is document.pdf"
	echo "-b	use when you tex file includes references from a bib file"
}

filename=main
outname=document
bibtex=0

while getopts ":hf:o:b" flag; do
	case $flag in
		h) get_help; exit ;;
		f) filename=$OPTARG ;;
		o) outname=$OPTARG ;;
		b) bibtex=1 ;;
		:) >&2 echo "Invalid option: $OPTARG requires an argument";
			get_help; exit ;;
		*) >&2 echo "Invalid option: -$OPTARG";
			get_help; exit ;;
		#?) >&2 echo "Invalid option: unknown option -$OPTARG"; exit ;;
	esac
done

# create .tex directory if needed
if [[ ! -d ".tex" ]]; then
	mkdir .tex
fi

# compile .tex into pdf with bibtex references
if [[ $bibtex -eq 0 ]]; then
	pdflatex ${filename}.tex
	bibtex ${filename}.aux
	pdflatex ${filename}.tex
else
	pdflatex ${filename}.tex
	pdflatex ${filename}.tex
fi

# get these out of sight
#rsync -a --files-from=.hide.list . .tex
mv *aux *log *toc *nav *out *snm *vrb .tex


# rename pdf
mv *.pdf ${outname}.pdf
